
version: 2

models:
  - name: DimCustomer
    description: "Dimension Table to load Customer data"
   

  - name: DimProduct
    description: "Dimension Table to load Customer data"

   
  - name: DimCampaign
    description: "Dimension Table to load Campaign data"


  - name: CustomerCampaignMapping
    description: "Dimension Table to map Customer and Campaign data"


  - name: FactSales
    description: "Fact Sales Table to load the Sales Data"

